step 2 failure

diff --git a/.github/workflows/status-check.yaml b/.github/workflows/status-check.yaml
--- a/.github/workflows/status-check.yaml
+++ b/.github/workflows/status-check.yaml
@@ -8,11 +8,15 @@ jobs:
     steps:
       - name: Step 1
         run: sleep 20
-      - name: Fail
+        #express de step laten falen om te testen
+      # - name: Fail
+      #   run: exit 1
+      - name: Step 2
+        id: step-2
         run: exit 1
       - name: Runs on Failure
-        if: failure()
-        run: echo 'Runs only on failure'
+        if: failure() && steps.step-2.conclusion == 'failure'
+        run: echo 'Step 2 has failed'
       - name: Runs on Succes
        #Not needed (default behaviour)
         if: success()
